server:
  port: 7002
eureka:
  instance:
    hostname: eureka-7002.com #Eureka服务端的名称
  client:
    register-with-eureka: false #是否向服务中心注册自己
    fetch-registry: false #如果为false表示自己就是一个注册中心
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7003.com:7003/eureka/
