server:
  port: 8082
mybatis:
  type-aliases-package: com.zxw.springcloud.pojo
  mapper-locations[0]: classpath:mapper/*.xml
spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud02?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/
  instance:
    instance-id: provider-dept-02
    prefer-ip-address: true
info:
  app.name: zhuxiaowu